### ✅ Crear nuevo usuario
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "nombre": "Juan Augusto Gallucci",
  "email": "galluccij15@gmail.com",
  "password": "juanchi03"
}

###

### 🔐 Login del usuario
POST http://localhost:3000/api/usuarios/login
Content-Type: application/json

{
  "email": "galluccij15@gmail.com",
  "password": "juanchi03"
}

###TIPO GASTOS

### 🟢 Crear tipo con color
POST http://localhost:3000/api/tipos
Content-Type: application/json

{
  "nombre": "Kiosko",
  "color": "#ffcc00",
  "usuarioId": 1
}

### ✏️ Editar tipo
PUT http://localhost:3000/api/tipos/1
Content-Type: application/json

{
  "nombre": "Supermercado",
  "color": "#00ccff"
}

### ❌ Eliminar tipo
DELETE http://localhost:3000/api/tipos/1


### GASTOS

### Crear un gasto
POST http://localhost:3000/api/gastos
Content-Type: application/json

{
   "nombre": "Fanta",
  "valor": 350,
  "usuarioId": 2,
  "tipoId": 2
}

### ✏️ Editar gasto
PUT http://localhost:3000/api/gastos/1
Content-Type: application/json

{
  "nombre": "Coca Cola",
  "valor": 300,
  "tipoId": 2
}

### ❌ Eliminar gasto
DELETE http://localhost:3000/api/gastos/1

### 🔎 Obtener tipos de gasto (con usuarioId)
GET http://localhost:3000/api/tipos?usuarioId=2

### 🔎 Obtener todos los gastos
GET http://localhost:3000/api/gastos/historico/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJnYWxsdWNjaWoxNUBnbWFpbC5jb20iLCJpYXQiOjE3NTA1NDc0MzMsImV4cCI6MTc1MTE1MjIzM30.BrbwknJf4h1rW2Uv1GTnqfbraFXR1NHmlsOJNyLQvpA